#!/bin/sh

ENABLED=yes
PROCS=AdGuardHome
ARGS="-w /opt/etc/AdGuardHome -l /opt/tmp/AdGuardHome.log --pidfile /opt/var/run/adguardhome.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/etc/AdGuardHome

. /opt/etc/init.d/rc.func
